// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class Activity
{
    
    private ActivityTypeList _type;
    
    private SchoolYearsList _year;
    
    private string _yearOtherDesc;
    
    private string _description;
    
    private string _organizationName;
    
    private Address _organizationAddress;
    
    private System.DateTime _startDate;
    
    private System.DateTime _endDate;
    
    private int _graduationRequirementHours;
    
    private int _summerHoursPerWeek;
    
    private int _summerWeeksPerYear;
    
    private int _schoolSeasonHoursPerWeek;
    
    private int _schoolSeasonWeeksPerYear;
    
    public Activity()
    {
        _organizationAddress = new Address();
    }
    
    public ActivityTypeList Type
    {
        get
        {
            return _type;
        }
        set
        {
            _type = value;
        }
    }
    
    public SchoolYearsList Year
    {
        get
        {
            return _year;
        }
        set
        {
            _year = value;
        }
    }
    
    public string YearOtherDesc
    {
        get
        {
            return _yearOtherDesc;
        }
        set
        {
            _yearOtherDesc = value;
        }
    }
    
    public string Description
    {
        get
        {
            return _description;
        }
        set
        {
            _description = value;
        }
    }
    
    public string OrganizationName
    {
        get
        {
            return _organizationName;
        }
        set
        {
            _organizationName = value;
        }
    }
    
    public Address OrganizationAddress
    {
        get
        {
            return _organizationAddress;
        }
        set
        {
            _organizationAddress = value;
        }
    }
    
    [XmlElementAttribute(DataType="date")]
    public System.DateTime StartDate
    {
        get
        {
            return _startDate;
        }
        set
        {
            _startDate = value;
        }
    }
    
    [XmlElementAttribute(DataType="date")]
    public System.DateTime EndDate
    {
        get
        {
            return _endDate;
        }
        set
        {
            _endDate = value;
        }
    }
    
    public int GraduationRequirementHours
    {
        get
        {
            return _graduationRequirementHours;
        }
        set
        {
            _graduationRequirementHours = value;
        }
    }
    
    public int SummerHoursPerWeek
    {
        get
        {
            return _summerHoursPerWeek;
        }
        set
        {
            _summerHoursPerWeek = value;
        }
    }
    
    public int SummerWeeksPerYear
    {
        get
        {
            return _summerWeeksPerYear;
        }
        set
        {
            _summerWeeksPerYear = value;
        }
    }
    
    public int SchoolSeasonHoursPerWeek
    {
        get
        {
            return _schoolSeasonHoursPerWeek;
        }
        set
        {
            _schoolSeasonHoursPerWeek = value;
        }
    }
    
    public int SchoolSeasonWeeksPerYear
    {
        get
        {
            return _schoolSeasonWeeksPerYear;
        }
        set
        {
            _schoolSeasonWeeksPerYear = value;
        }
    }
}
}
#pragma warning restore
