// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum ActivityTypeList
{
    
    /// <remarks/>
    [XmlEnumAttribute("Community service or volunteering")]
    Communityserviceorvolunteering,
    
    /// <remarks/>
    Employment,
    
    /// <remarks/>
    Athletics,
    
    /// <remarks/>
    Arts,
    
    /// <remarks/>
    [XmlEnumAttribute("School organization or club")]
    Schoolorganizationorclub,
    
    /// <remarks/>
    [XmlEnumAttribute("Major award or honor")]
    Majorawardorhonor,
    
    /// <remarks/>
    [XmlEnumAttribute("College readiness program")]
    Collegereadinessprogram,
    
    /// <remarks/>
    [XmlEnumAttribute("Foreign travel or study")]
    Foreigntravelorstudy,
    
    /// <remarks/>
    [XmlEnumAttribute("Home and family responsibilities")]
    Homeandfamilyresponsibilities,
    
    /// <remarks/>
    Hobby,
    
    /// <remarks/>
    Government,
    
    /// <remarks/>
    Internship,
    
    /// <remarks/>
    Military,
    
    /// <remarks/>
    [XmlEnumAttribute("Other activity")]
    Otheractivity,
}
}
#pragma warning restore
