// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum AttachedFileTypeList
{
    
    /// <remarks/>
    [XmlEnumAttribute("Student Aid Report (SAR)")]
    StudentAidReportSAR,
    
    /// <remarks/>
    Transcript,
    
    /// <remarks/>
    FAFSA,
    
    /// <remarks/>
    Picture,
    
    /// <remarks/>
    [XmlEnumAttribute("Recommendation/Reference Letter")]
    RecommendationReferenceLetter,
    
    /// <remarks/>
    [XmlEnumAttribute("Portfolio Document")]
    PortfolioDocument,
    
    /// <remarks/>
    [XmlEnumAttribute("Diploma Certificate")]
    DiplomaCertificate,
    
    /// <remarks/>
    [XmlEnumAttribute("Degree Certificate")]
    DegreeCertificate,
    
    /// <remarks/>
    [XmlEnumAttribute("Proof of Achievement")]
    ProofofAchievement,
    
    /// <remarks/>
    [XmlEnumAttribute("School Acceptance Letter")]
    SchoolAcceptanceLetter,
    
    /// <remarks/>
    [XmlEnumAttribute("Medical Document")]
    MedicalDocument,
    
    /// <remarks/>
    [XmlEnumAttribute("Proof of Employment")]
    ProofofEmployment,
    
    /// <remarks/>
    Video,
    
    /// <remarks/>
    Audio,
    
    /// <remarks/>
    Other,
}
}
#pragma warning restore
