// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class BirthPlace
{
    
    private string _city;
    
    private string _stateOrProvince;
    
    private string _country;
    
    public string City
    {
        get
        {
            return _city;
        }
        set
        {
            _city = value;
        }
    }
    
    public string StateOrProvince
    {
        get
        {
            return _stateOrProvince;
        }
        set
        {
            _stateOrProvince = value;
        }
    }
    
    public string Country
    {
        get
        {
            return _country;
        }
        set
        {
            _country = value;
        }
    }
}
}
#pragma warning restore
