// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum ClassList
{
    
    /// <remarks/>
    [XmlEnumAttribute("English grade 9")]
    Englishgrade9,
    
    /// <remarks/>
    [XmlEnumAttribute("English grade 10")]
    Englishgrade10,
    
    /// <remarks/>
    [XmlEnumAttribute("English grade 11")]
    Englishgrade11,
    
    /// <remarks/>
    [XmlEnumAttribute("English grade 12")]
    Englishgrade12,
    
    /// <remarks/>
    [XmlEnumAttribute("Algebra 1")]
    Algebra1,
    
    /// <remarks/>
    Geometry,
    
    /// <remarks/>
    [XmlEnumAttribute("Algebra 2")]
    Algebra2,
    
    /// <remarks/>
    Trigonometry,
    
    /// <remarks/>
    [XmlEnumAttribute("Pre-Calculus")]
    PreCalculus,
    
    /// <remarks/>
    Calculus,
    
    /// <remarks/>
    [XmlEnumAttribute("Other advanced math")]
    Otheradvancedmath,
    
    /// <remarks/>
    [XmlEnumAttribute("Computer science")]
    Computerscience,
    
    /// <remarks/>
    [XmlEnumAttribute("Earth or general science")]
    Earthorgeneralscience,
    
    /// <remarks/>
    Biology,
    
    /// <remarks/>
    Chemistry,
    
    /// <remarks/>
    Physics,
    
    /// <remarks/>
    Anatomy,
    
    /// <remarks/>
    Physiology,
    
    /// <remarks/>
    [XmlEnumAttribute("Other science")]
    Otherscience,
    
    /// <remarks/>
    [XmlEnumAttribute("U.S. History")]
    USHistory,
    
    /// <remarks/>
    [XmlEnumAttribute("World History")]
    WorldHistory,
    
    /// <remarks/>
    [XmlEnumAttribute("Government or civics")]
    Governmentorcivics,
    
    /// <remarks/>
    Economics,
    
    /// <remarks/>
    [XmlEnumAttribute("World culture or global studies")]
    Worldcultureorglobalstudies,
    
    /// <remarks/>
    Geography,
    
    /// <remarks/>
    Psychology,
    
    /// <remarks/>
    Sociology,
    
    /// <remarks/>
    [XmlEnumAttribute("Foreign language")]
    Foreignlanguage,
    
    /// <remarks/>
    Philosophy,
    
    /// <remarks/>
    [XmlEnumAttribute("Other social studies")]
    Othersocialstudies,
    
    /// <remarks/>
    [XmlEnumAttribute("Other courses")]
    Othercourses,
}
}
#pragma warning restore
