// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum ClassTypeList
{
    
    /// <remarks/>
    Senior,
    
    /// <remarks/>
    Honors,
    
    /// <remarks/>
    AP,
    
    /// <remarks/>
    IB,
    
    /// <remarks/>
    [XmlEnumAttribute("Dual enrollment")]
    Dualenrollment,
    
    /// <remarks/>
    [XmlEnumAttribute("Special education")]
    Specialeducation,
    
    /// <remarks/>
    Remedial,
    
    /// <remarks/>
    Other,
}
}
#pragma warning restore
