// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class CollegeReadinessProgram
{
    
    private CollegeReadinessProgramList _programName;
    
    private string _programOtherDesc;
    
    private string _counselorFirstName;
    
    private string _counselorLastName;
    
    private string _counselorEmail;
    
    private string _lengthOfParticipation;
    
    public CollegeReadinessProgramList ProgramName
    {
        get
        {
            return _programName;
        }
        set
        {
            _programName = value;
        }
    }
    
    public string ProgramOtherDesc
    {
        get
        {
            return _programOtherDesc;
        }
        set
        {
            _programOtherDesc = value;
        }
    }
    
    public string CounselorFirstName
    {
        get
        {
            return _counselorFirstName;
        }
        set
        {
            _counselorFirstName = value;
        }
    }
    
    public string CounselorLastName
    {
        get
        {
            return _counselorLastName;
        }
        set
        {
            _counselorLastName = value;
        }
    }
    
    public string CounselorEmail
    {
        get
        {
            return _counselorEmail;
        }
        set
        {
            _counselorEmail = value;
        }
    }
    
    [XmlElementAttribute(DataType="duration")]
    public string LengthOfParticipation
    {
        get
        {
            return _lengthOfParticipation;
        }
        set
        {
            _lengthOfParticipation = value;
        }
    }
}
}
#pragma warning restore
