// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum CollegeReadinessProgramList
{
    
    /// <remarks/>
    [XmlEnumAttribute("AP Strategies")]
    APStrategies,
    
    /// <remarks/>
    Aspire,
    
    /// <remarks/>
    AVID,
    
    /// <remarks/>
    [XmlEnumAttribute("GEAR UP")]
    GEARUP,
    
    /// <remarks/>
    [XmlEnumAttribute("Green Dot Public Schools")]
    GreenDotPublicSchools,
    
    /// <remarks/>
    [XmlEnumAttribute("KIPP Academy")]
    KIPPAcademy,
    
    /// <remarks/>
    [XmlEnumAttribute("Noble Charter")]
    NobleCharter,
    
    /// <remarks/>
    [XmlEnumAttribute("Philadelphia Futures")]
    PhiladelphiaFutures,
    
    /// <remarks/>
    PUC,
    
    /// <remarks/>
    [XmlEnumAttribute("Upward Bound")]
    UpwardBound,
    
    /// <remarks/>
    [XmlEnumAttribute("Upward Bound - Math and Science")]
    UpwardBoundMathandScience,
    
    /// <remarks/>
    [XmlEnumAttribute("YES Charter")]
    YESCharter,
    
    /// <remarks/>
    [XmlEnumAttribute("Breakthrough Austin")]
    BreakthroughAustin,
    
    /// <remarks/>
    [XmlEnumAttribute("IDEA Academy")]
    IDEAAcademy,
    
    /// <remarks/>
    Other,
}
}
#pragma warning restore
