// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class CollegeChoice
{
    
    private string _collegeName;
    
    private string _nCESCode;
    
    private string _cEEBCode;
    
    private int _collegeChoiceRank;
    
    private ApplicationStatusList _collegeApplicationStatus;
    
    private string _collegeApplicationStatusOtherDesc;
    
    public string CollegeName
    {
        get
        {
            return _collegeName;
        }
        set
        {
            _collegeName = value;
        }
    }
    
    public string NCESCode
    {
        get
        {
            return _nCESCode;
        }
        set
        {
            _nCESCode = value;
        }
    }
    
    public string CEEBCode
    {
        get
        {
            return _cEEBCode;
        }
        set
        {
            _cEEBCode = value;
        }
    }
    
    public int CollegeChoiceRank
    {
        get
        {
            return _collegeChoiceRank;
        }
        set
        {
            _collegeChoiceRank = value;
        }
    }
    
    public ApplicationStatusList CollegeApplicationStatus
    {
        get
        {
            return _collegeApplicationStatus;
        }
        set
        {
            _collegeApplicationStatus = value;
        }
    }
    
    public string CollegeApplicationStatusOtherDesc
    {
        get
        {
            return _collegeApplicationStatusOtherDesc;
        }
        set
        {
            _collegeApplicationStatusOtherDesc = value;
        }
    }
}
}
#pragma warning restore
