// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class ContactInfo
{
    
    private string _email;
    
    private string _primaryPhoneNumber;
    
    private bool _isPrimaryPhoneTextCapable;
    
    private string _alternatePhoneNumber;
    
    private bool _isAlternatePhoneTextCapable;
    
    private string _faxNumber;
    
    private string _otherMessagingAddress;
    
    private string _otherMessagingAddressType;
    
    private ContactMethodsList _preferredContactMethod;
    
    public string Email
    {
        get
        {
            return _email;
        }
        set
        {
            _email = value;
        }
    }
    
    public string PrimaryPhoneNumber
    {
        get
        {
            return _primaryPhoneNumber;
        }
        set
        {
            _primaryPhoneNumber = value;
        }
    }
    
    public bool IsPrimaryPhoneTextCapable
    {
        get
        {
            return _isPrimaryPhoneTextCapable;
        }
        set
        {
            _isPrimaryPhoneTextCapable = value;
        }
    }
    
    public string AlternatePhoneNumber
    {
        get
        {
            return _alternatePhoneNumber;
        }
        set
        {
            _alternatePhoneNumber = value;
        }
    }
    
    public bool IsAlternatePhoneTextCapable
    {
        get
        {
            return _isAlternatePhoneTextCapable;
        }
        set
        {
            _isAlternatePhoneTextCapable = value;
        }
    }
    
    public string FaxNumber
    {
        get
        {
            return _faxNumber;
        }
        set
        {
            _faxNumber = value;
        }
    }
    
    public string OtherMessagingAddress
    {
        get
        {
            return _otherMessagingAddress;
        }
        set
        {
            _otherMessagingAddress = value;
        }
    }
    
    public string OtherMessagingAddressType
    {
        get
        {
            return _otherMessagingAddressType;
        }
        set
        {
            _otherMessagingAddressType = value;
        }
    }
    
    public ContactMethodsList PreferredContactMethod
    {
        get
        {
            return _preferredContactMethod;
        }
        set
        {
            _preferredContactMethod = value;
        }
    }
}
}
#pragma warning restore
