// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum CultureCodeList
{
    
    /// <remarks/>
    [XmlEnumAttribute("en-US")]
    enUS,
    
    /// <remarks/>
    [XmlEnumAttribute("en-CA")]
    enCA,
    
    /// <remarks/>
    [XmlEnumAttribute("af-ZA")]
    afZA,
    
    /// <remarks/>
    [XmlEnumAttribute("sq-AL")]
    sqAL,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-DZ")]
    arDZ,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-BH")]
    arBH,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-EG")]
    arEG,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-IQ")]
    arIQ,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-JO")]
    arJO,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-KW")]
    arKW,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-LB")]
    arLB,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-LY")]
    arLY,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-MA")]
    arMA,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-OM")]
    arOM,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-QA")]
    arQA,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-SA")]
    arSA,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-SY")]
    arSY,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-TN")]
    arTN,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-AE")]
    arAE,
    
    /// <remarks/>
    [XmlEnumAttribute("ar-YE")]
    arYE,
    
    /// <remarks/>
    [XmlEnumAttribute("hy-AM")]
    hyAM,
    
    /// <remarks/>
    [XmlEnumAttribute("Cy-az-AZ")]
    CyazAZ,
    
    /// <remarks/>
    [XmlEnumAttribute("Lt-az-AZ")]
    LtazAZ,
    
    /// <remarks/>
    [XmlEnumAttribute("eu-ES")]
    euES,
    
    /// <remarks/>
    [XmlEnumAttribute("be-BY")]
    beBY,
    
    /// <remarks/>
    [XmlEnumAttribute("bg-BG")]
    bgBG,
    
    /// <remarks/>
    [XmlEnumAttribute("ca-ES")]
    caES,
    
    /// <remarks/>
    [XmlEnumAttribute("zh-CN")]
    zhCN,
    
    /// <remarks/>
    [XmlEnumAttribute("zh-HK")]
    zhHK,
    
    /// <remarks/>
    [XmlEnumAttribute("zh-MO")]
    zhMO,
    
    /// <remarks/>
    [XmlEnumAttribute("zh-SG")]
    zhSG,
    
    /// <remarks/>
    [XmlEnumAttribute("zh-TW")]
    zhTW,
    
    /// <remarks/>
    [XmlEnumAttribute("zh-CHS")]
    zhCHS,
    
    /// <remarks/>
    [XmlEnumAttribute("zh-CHT")]
    zhCHT,
    
    /// <remarks/>
    [XmlEnumAttribute("hr-HR")]
    hrHR,
    
    /// <remarks/>
    [XmlEnumAttribute("cs-CZ")]
    csCZ,
    
    /// <remarks/>
    [XmlEnumAttribute("da-DK")]
    daDK,
    
    /// <remarks/>
    [XmlEnumAttribute("nl-BE")]
    nlBE,
    
    /// <remarks/>
    [XmlEnumAttribute("nl-NL")]
    nlNL,
    
    /// <remarks/>
    [XmlEnumAttribute("en-AU")]
    enAU,
    
    /// <remarks/>
    [XmlEnumAttribute("en-BZ")]
    enBZ,
    
    /// <remarks/>
    [XmlEnumAttribute("en-CB")]
    enCB,
    
    /// <remarks/>
    [XmlEnumAttribute("en-IE")]
    enIE,
    
    /// <remarks/>
    [XmlEnumAttribute("en-JM")]
    enJM,
    
    /// <remarks/>
    [XmlEnumAttribute("en-NZ")]
    enNZ,
    
    /// <remarks/>
    [XmlEnumAttribute("en-PH")]
    enPH,
    
    /// <remarks/>
    [XmlEnumAttribute("en-ZA")]
    enZA,
    
    /// <remarks/>
    [XmlEnumAttribute("en-TT")]
    enTT,
    
    /// <remarks/>
    [XmlEnumAttribute("en-GB")]
    enGB,
    
    /// <remarks/>
    [XmlEnumAttribute("en-ZW")]
    enZW,
    
    /// <remarks/>
    [XmlEnumAttribute("et-EE")]
    etEE,
    
    /// <remarks/>
    [XmlEnumAttribute("fo-FO")]
    foFO,
    
    /// <remarks/>
    [XmlEnumAttribute("fa-IR")]
    faIR,
    
    /// <remarks/>
    [XmlEnumAttribute("fi-FI")]
    fiFI,
    
    /// <remarks/>
    [XmlEnumAttribute("fr-BE")]
    frBE,
    
    /// <remarks/>
    [XmlEnumAttribute("fr-CA")]
    frCA,
    
    /// <remarks/>
    [XmlEnumAttribute("fr-FR")]
    frFR,
    
    /// <remarks/>
    [XmlEnumAttribute("fr-LU")]
    frLU,
    
    /// <remarks/>
    [XmlEnumAttribute("fr-MC")]
    frMC,
    
    /// <remarks/>
    [XmlEnumAttribute("fr-CH")]
    frCH,
    
    /// <remarks/>
    [XmlEnumAttribute("gl-ES")]
    glES,
    
    /// <remarks/>
    [XmlEnumAttribute("ka-GE")]
    kaGE,
    
    /// <remarks/>
    [XmlEnumAttribute("de-AT")]
    deAT,
    
    /// <remarks/>
    [XmlEnumAttribute("de-DE")]
    deDE,
    
    /// <remarks/>
    [XmlEnumAttribute("de-LI")]
    deLI,
    
    /// <remarks/>
    [XmlEnumAttribute("de-LU")]
    deLU,
    
    /// <remarks/>
    [XmlEnumAttribute("de-CH")]
    deCH,
    
    /// <remarks/>
    [XmlEnumAttribute("el-GR")]
    elGR,
    
    /// <remarks/>
    [XmlEnumAttribute("gu-IN")]
    guIN,
    
    /// <remarks/>
    [XmlEnumAttribute("he-IL")]
    heIL,
    
    /// <remarks/>
    [XmlEnumAttribute("hi-IN")]
    hiIN,
    
    /// <remarks/>
    [XmlEnumAttribute("hu-HU")]
    huHU,
    
    /// <remarks/>
    [XmlEnumAttribute("is-IS")]
    isIS,
    
    /// <remarks/>
    [XmlEnumAttribute("id-ID")]
    idID,
    
    /// <remarks/>
    [XmlEnumAttribute("it-IT")]
    itIT,
    
    /// <remarks/>
    [XmlEnumAttribute("it-CH")]
    itCH,
    
    /// <remarks/>
    [XmlEnumAttribute("ja-JP")]
    jaJP,
    
    /// <remarks/>
    [XmlEnumAttribute("kn-IN")]
    knIN,
    
    /// <remarks/>
    [XmlEnumAttribute("kk-KZ")]
    kkKZ,
    
    /// <remarks/>
    [XmlEnumAttribute("ko-KR")]
    koKR,
    
    /// <remarks/>
    [XmlEnumAttribute("ky-KZ")]
    kyKZ,
    
    /// <remarks/>
    [XmlEnumAttribute("lv-LV")]
    lvLV,
    
    /// <remarks/>
    [XmlEnumAttribute("lt-LT")]
    ltLT,
    
    /// <remarks/>
    [XmlEnumAttribute("mk-MK")]
    mkMK,
    
    /// <remarks/>
    [XmlEnumAttribute("ms-BN")]
    msBN,
    
    /// <remarks/>
    [XmlEnumAttribute("ms-MY")]
    msMY,
    
    /// <remarks/>
    [XmlEnumAttribute("mr-IN")]
    mrIN,
    
    /// <remarks/>
    [XmlEnumAttribute("mn-MN")]
    mnMN,
    
    /// <remarks/>
    [XmlEnumAttribute("nb-NO")]
    nbNO,
    
    /// <remarks/>
    [XmlEnumAttribute("nn-NO")]
    nnNO,
    
    /// <remarks/>
    [XmlEnumAttribute("pl-PL")]
    plPL,
    
    /// <remarks/>
    [XmlEnumAttribute("pt-BR")]
    ptBR,
    
    /// <remarks/>
    [XmlEnumAttribute("pt-PT")]
    ptPT,
    
    /// <remarks/>
    [XmlEnumAttribute("pa-IN")]
    paIN,
    
    /// <remarks/>
    [XmlEnumAttribute("ro-RO")]
    roRO,
    
    /// <remarks/>
    [XmlEnumAttribute("ru-RU")]
    ruRU,
    
    /// <remarks/>
    [XmlEnumAttribute("sa-IN")]
    saIN,
    
    /// <remarks/>
    [XmlEnumAttribute("Cy-sr-SP")]
    CysrSP,
    
    /// <remarks/>
    [XmlEnumAttribute("Lt-sr-SP")]
    LtsrSP,
    
    /// <remarks/>
    [XmlEnumAttribute("sk-SK")]
    skSK,
    
    /// <remarks/>
    [XmlEnumAttribute("sl-SI")]
    slSI,
    
    /// <remarks/>
    [XmlEnumAttribute("es-AR")]
    esAR,
    
    /// <remarks/>
    [XmlEnumAttribute("es-BO")]
    esBO,
    
    /// <remarks/>
    [XmlEnumAttribute("es-CL")]
    esCL,
    
    /// <remarks/>
    [XmlEnumAttribute("es-CO")]
    esCO,
    
    /// <remarks/>
    [XmlEnumAttribute("es-CR")]
    esCR,
    
    /// <remarks/>
    [XmlEnumAttribute("es-DO")]
    esDO,
    
    /// <remarks/>
    [XmlEnumAttribute("es-EC")]
    esEC,
    
    /// <remarks/>
    [XmlEnumAttribute("es-SV")]
    esSV,
    
    /// <remarks/>
    [XmlEnumAttribute("es-GT")]
    esGT,
    
    /// <remarks/>
    [XmlEnumAttribute("es-HN")]
    esHN,
    
    /// <remarks/>
    [XmlEnumAttribute("es-MX")]
    esMX,
    
    /// <remarks/>
    [XmlEnumAttribute("es-NI")]
    esNI,
    
    /// <remarks/>
    [XmlEnumAttribute("es-PA")]
    esPA,
    
    /// <remarks/>
    [XmlEnumAttribute("es-PY")]
    esPY,
    
    /// <remarks/>
    [XmlEnumAttribute("es-PE")]
    esPE,
    
    /// <remarks/>
    [XmlEnumAttribute("es-PR")]
    esPR,
    
    /// <remarks/>
    [XmlEnumAttribute("es-ES")]
    esES,
    
    /// <remarks/>
    [XmlEnumAttribute("es-UY")]
    esUY,
    
    /// <remarks/>
    [XmlEnumAttribute("es-VE")]
    esVE,
    
    /// <remarks/>
    [XmlEnumAttribute("sw-KE")]
    swKE,
    
    /// <remarks/>
    [XmlEnumAttribute("sv-FI")]
    svFI,
    
    /// <remarks/>
    [XmlEnumAttribute("sv-SE")]
    svSE,
    
    /// <remarks/>
    [XmlEnumAttribute("ta-IN")]
    taIN,
    
    /// <remarks/>
    [XmlEnumAttribute("tt-RU")]
    ttRU,
    
    /// <remarks/>
    [XmlEnumAttribute("te-IN")]
    teIN,
    
    /// <remarks/>
    [XmlEnumAttribute("th-TH")]
    thTH,
    
    /// <remarks/>
    [XmlEnumAttribute("tr-TR")]
    trTR,
    
    /// <remarks/>
    [XmlEnumAttribute("uk-UA")]
    ukUA,
    
    /// <remarks/>
    [XmlEnumAttribute("ur-PK")]
    urPK,
    
    /// <remarks/>
    [XmlEnumAttribute("Cy-uz-UZ")]
    CyuzUZ,
    
    /// <remarks/>
    [XmlEnumAttribute("Lt-uz-UZ")]
    LtuzUZ,
    
    /// <remarks/>
    [XmlEnumAttribute("vi-VN")]
    viVN,
}
}
#pragma warning restore
