// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum EducationLevelsList
{
    
    /// <remarks/>
    [XmlEnumAttribute("No school")]
    Noschool,
    
    /// <remarks/>
    [XmlEnumAttribute("Elementary school")]
    Elementaryschool,
    
    /// <remarks/>
    [XmlEnumAttribute("Middle school")]
    Middleschool,
    
    /// <remarks/>
    [XmlEnumAttribute("Some high school")]
    Somehighschool,
    
    /// <remarks/>
    [XmlEnumAttribute("High school graduate")]
    Highschoolgraduate,
    
    /// <remarks/>
    [XmlEnumAttribute("Some college")]
    Somecollege,
    
    /// <remarks/>
    [XmlEnumAttribute("Associate\'s degree")]
    Associatesdegree,
    
    /// <remarks/>
    [XmlEnumAttribute("Bachelor\'s degree")]
    Bachelorsdegree,
    
    /// <remarks/>
    [XmlEnumAttribute("Master\'s degree")]
    Mastersdegree,
    
    /// <remarks/>
    Doctorate,
    
    /// <remarks/>
    [XmlEnumAttribute("Professional degree")]
    Professionaldegree,
    
    /// <remarks/>
    Unknown,
    
    /// <remarks/>
    Other,
}
}
#pragma warning restore
