// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class EducationLevel
{
    
    private EducationLevelsList _educationLevel1;
    
    private string _educationLevelOther;
    
    [XmlElementAttribute("EducationLevel")]
    public EducationLevelsList EducationLevel1
    {
        get
        {
            return _educationLevel1;
        }
        set
        {
            _educationLevel1 = value;
        }
    }
    
    public string EducationLevelOther
    {
        get
        {
            return _educationLevelOther;
        }
        set
        {
            _educationLevelOther = value;
        }
    }
}
}
#pragma warning restore
