// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class Enrollment
{
    
    private School _school;
    
    private SchoolProgramTypesList _schoolProgram;
    
    private string _enrollmentOtherDesc;
    
    private System.DateTime _expectedGraduationDate;
    
    public Enrollment()
    {
        _school = new School();
    }
    
    public School School
    {
        get
        {
            return _school;
        }
        set
        {
            _school = value;
        }
    }
    
    public SchoolProgramTypesList SchoolProgram
    {
        get
        {
            return _schoolProgram;
        }
        set
        {
            _schoolProgram = value;
        }
    }
    
    public string EnrollmentOtherDesc
    {
        get
        {
            return _enrollmentOtherDesc;
        }
        set
        {
            _enrollmentOtherDesc = value;
        }
    }
    
    [XmlElementAttribute(DataType="date")]
    public System.DateTime ExpectedGraduationDate
    {
        get
        {
            return _expectedGraduationDate;
        }
        set
        {
            _expectedGraduationDate = value;
        }
    }
}
}
#pragma warning restore
