// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class Essay
{
    
    private EssayTypes _essayType;
    
    private string _essayTypeOtherDesc;
    
    private string _essayContent;
    
    public EssayTypes EssayType
    {
        get
        {
            return _essayType;
        }
        set
        {
            _essayType = value;
        }
    }
    
    public string EssayTypeOtherDesc
    {
        get
        {
            return _essayTypeOtherDesc;
        }
        set
        {
            _essayTypeOtherDesc = value;
        }
    }
    
    public string EssayContent
    {
        get
        {
            return _essayContent;
        }
        set
        {
            _essayContent = value;
        }
    }
}
}
#pragma warning restore
