// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum EssayTypes
{
    
    /// <remarks/>
    [XmlEnumAttribute("Post graduation and career goals")]
    Postgraduationandcareergoals,
    
    /// <remarks/>
    [XmlEnumAttribute("Education plans beyond graduation")]
    Educationplansbeyondgraduation,
    
    /// <remarks/>
    [XmlEnumAttribute("Leadership experiences")]
    Leadershipexperiences,
    
    /// <remarks/>
    [XmlEnumAttribute("Organizational leadership roles and outcomes")]
    Organizationalleadershiprolesandoutcomes,
    
    /// <remarks/>
    [XmlEnumAttribute("Lifetime goals and objectives")]
    Lifetimegoalsandobjectives,
    
    /// <remarks/>
    [XmlEnumAttribute("Personal background or history")]
    Personalbackgroundorhistory,
    
    /// <remarks/>
    [XmlEnumAttribute("Family background or history")]
    Familybackgroundorhistory,
    
    /// <remarks/>
    [XmlEnumAttribute("Affecting the lives of others")]
    Affectingthelivesofothers,
    
    /// <remarks/>
    [XmlEnumAttribute("Community contribution")]
    Communitycontribution,
    
    /// <remarks/>
    [XmlEnumAttribute("Community leadership")]
    Communityleadership,
    
    /// <remarks/>
    [XmlEnumAttribute("The community impact upon the student")]
    Thecommunityimpactuponthestudent,
    
    /// <remarks/>
    [XmlEnumAttribute("Favorite activity")]
    Favoriteactivity,
    
    /// <remarks/>
    [XmlEnumAttribute("Home responsibilities")]
    Homeresponsibilities,
    
    /// <remarks/>
    [XmlEnumAttribute("Overcoming adversity")]
    Overcomingadversity,
    
    /// <remarks/>
    [XmlEnumAttribute("Work responsibilities")]
    Workresponsibilities,
    
    /// <remarks/>
    [XmlEnumAttribute("Personal achievements, awards, and honors")]
    Personalachievementsawardsandhonors,
    
    /// <remarks/>
    [XmlEnumAttribute("Special circumstances affecting college finance")]
    Specialcircumstancesaffectingcollegefinance,
    
    /// <remarks/>
    [XmlEnumAttribute("Why student deserves the scholarship")]
    Whystudentdeservesthescholarship,
    
    /// <remarks/>
    [XmlEnumAttribute("How ethnicity shaped the student")]
    Howethnicityshapedthestudent,
    
    /// <remarks/>
    [XmlEnumAttribute("How college readiness programs helped the student")]
    Howcollegereadinessprogramshelpedthestudent,
    
    /// <remarks/>
    [XmlEnumAttribute("Athletic involvement, achievements, and impact on the student")]
    Athleticinvolvementachievementsandimpactonthestudent,
    
    /// <remarks/>
    [XmlEnumAttribute("Special programs participation and outcomes")]
    Specialprogramsparticipationandoutcomes,
    
    /// <remarks/>
    [XmlEnumAttribute("Explanation of student\'s college choices")]
    Explanationofstudentscollegechoices,
    
    /// <remarks/>
    [XmlEnumAttribute("Explanation of student\'s major choices")]
    Explanationofstudentsmajorchoices,
    
    /// <remarks/>
    [XmlEnumAttribute("Failures and the resulting lessons learned")]
    Failuresandtheresultinglessonslearned,
    
    /// <remarks/>
    [XmlEnumAttribute("How the student challenged herself")]
    Howthestudentchallengedherself,
    
    /// <remarks/>
    [XmlEnumAttribute("Disciplinary or legal problems")]
    Disciplinaryorlegalproblems,
    
    /// <remarks/>
    Other,
}
}
#pragma warning restore
