// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class Ethnicity
{
    
    private List<EthnicitiesList> _ethnicity1;
    
    private string _ethnicityOtherDesc;
    
    public Ethnicity()
    {
        _ethnicity1 = new List<EthnicitiesList>();
    }
    
    [XmlElementAttribute("Ethnicity")]
    public List<EthnicitiesList> Ethnicity1
    {
        get
        {
            return _ethnicity1;
        }
        set
        {
            _ethnicity1 = value;
        }
    }
    
    public string EthnicityOtherDesc
    {
        get
        {
            return _ethnicityOtherDesc;
        }
        set
        {
            _ethnicityOtherDesc = value;
        }
    }
}
}
#pragma warning restore
