// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum EthnicitiesList
{
    
    /// <remarks/>
    African,
    
    /// <remarks/>
    AfricanAmerican,
    
    /// <remarks/>
    Albanian,
    
    /// <remarks/>
    American,
    
    /// <remarks/>
    AmericanIndian,
    
    /// <remarks/>
    Arab,
    
    /// <remarks/>
    Armenian,
    
    /// <remarks/>
    Asian,
    
    /// <remarks/>
    AsianIndian,
    
    /// <remarks/>
    Austrian,
    
    /// <remarks/>
    Belgian,
    
    /// <remarks/>
    Brazilian,
    
    /// <remarks/>
    British,
    
    /// <remarks/>
    Cambodian,
    
    /// <remarks/>
    Canadian,
    
    /// <remarks/>
    Chinese,
    
    /// <remarks/>
    Colombian,
    
    /// <remarks/>
    Croatian,
    
    /// <remarks/>
    Cuban,
    
    /// <remarks/>
    Czech,
    
    /// <remarks/>
    Czechoslovakian,
    
    /// <remarks/>
    Danish,
    
    /// <remarks/>
    Dominican,
    
    /// <remarks/>
    Dutch,
    
    /// <remarks/>
    Ecuadorian,
    
    /// <remarks/>
    Egyptian,
    
    /// <remarks/>
    English,
    
    /// <remarks/>
    European,
    
    /// <remarks/>
    Filipino,
    
    /// <remarks/>
    Finnish,
    
    /// <remarks/>
    French,
    
    /// <remarks/>
    FrenchCanadian,
    
    /// <remarks/>
    German,
    
    /// <remarks/>
    Greek,
    
    /// <remarks/>
    Guatemalan,
    
    /// <remarks/>
    Guyanese,
    
    /// <remarks/>
    Haitian,
    
    /// <remarks/>
    Hawaiian,
    
    /// <remarks/>
    Hispanic,
    
    /// <remarks/>
    Hmong,
    
    /// <remarks/>
    Honduran,
    
    /// <remarks/>
    Hungarian,
    
    /// <remarks/>
    Iranian,
    
    /// <remarks/>
    Irish,
    
    /// <remarks/>
    Israeli,
    
    /// <remarks/>
    Italian,
    
    /// <remarks/>
    Jamaican,
    
    /// <remarks/>
    Japanese,
    
    /// <remarks/>
    Korean,
    
    /// <remarks/>
    Laotian,
    
    /// <remarks/>
    LatinAmerican,
    
    /// <remarks/>
    Lebanese,
    
    /// <remarks/>
    Lithuanian,
    
    /// <remarks/>
    Mexican,
    
    /// <remarks/>
    Nicaraguan,
    
    /// <remarks/>
    Nigerian,
    
    /// <remarks/>
    NorthernEuropean,
    
    /// <remarks/>
    Norwegian,
    
    /// <remarks/>
    Pakistani,
    
    /// <remarks/>
    Panamanian,
    
    /// <remarks/>
    Peruvian,
    
    /// <remarks/>
    Polish,
    
    /// <remarks/>
    Portuguese,
    
    /// <remarks/>
    PuertoRican,
    
    /// <remarks/>
    Romanian,
    
    /// <remarks/>
    Russian,
    
    /// <remarks/>
    Salvadoran,
    
    /// <remarks/>
    Scandinavian,
    
    /// <remarks/>
    [XmlEnumAttribute("Scotch-Irish")]
    ScotchIrish,
    
    /// <remarks/>
    Scottish,
    
    /// <remarks/>
    Serbian,
    
    /// <remarks/>
    Slavic,
    
    /// <remarks/>
    Slovak,
    
    /// <remarks/>
    Slovene,
    
    /// <remarks/>
    Spaniard,
    
    /// <remarks/>
    Spanish,
    
    /// <remarks/>
    Swedish,
    
    /// <remarks/>
    Swiss,
    
    /// <remarks/>
    Syrian,
    
    /// <remarks/>
    Taiwanese,
    
    /// <remarks/>
    Thai,
    
    /// <remarks/>
    TrinidadianAndTobagonian,
    
    /// <remarks/>
    Turkish,
    
    /// <remarks/>
    Ukrainian,
    
    /// <remarks/>
    Vietnamese,
    
    /// <remarks/>
    Welsh,
    
    /// <remarks/>
    WestIndian,
    
    /// <remarks/>
    WesternEuropean,
    
    /// <remarks/>
    Yugoslavian,
    
    /// <remarks/>
    Apache,
    
    /// <remarks/>
    Blackfeet,
    
    /// <remarks/>
    Cherokee,
    
    /// <remarks/>
    Cheyenne,
    
    /// <remarks/>
    Chickasaw,
    
    /// <remarks/>
    Chippewa,
    
    /// <remarks/>
    Choctaw,
    
    /// <remarks/>
    Colville,
    
    /// <remarks/>
    Comanche,
    
    /// <remarks/>
    Cree,
    
    /// <remarks/>
    Creek,
    
    /// <remarks/>
    Crow,
    
    /// <remarks/>
    Delaware,
    
    /// <remarks/>
    Houma,
    
    /// <remarks/>
    Iroquois,
    
    /// <remarks/>
    Kiowa,
    
    /// <remarks/>
    [XmlEnumAttribute("Latin American Indian")]
    LatinAmericanIndian,
    
    /// <remarks/>
    Lumbee,
    
    /// <remarks/>
    Menominee,
    
    /// <remarks/>
    Navajo,
    
    /// <remarks/>
    Osage,
    
    /// <remarks/>
    Ottawa,
    
    /// <remarks/>
    Paiute,
    
    /// <remarks/>
    Pima,
    
    /// <remarks/>
    Potawatomi,
    
    /// <remarks/>
    Pueblo,
    
    /// <remarks/>
    [XmlEnumAttribute("Puget Sound Salish")]
    PugetSoundSalish,
    
    /// <remarks/>
    Seminole,
    
    /// <remarks/>
    Shoshone,
    
    /// <remarks/>
    Sioux,
    
    /// <remarks/>
    [XmlEnumAttribute("Tohono O’odham")]
    TohonoOodham,
    
    /// <remarks/>
    Ute,
    
    /// <remarks/>
    Yakama,
    
    /// <remarks/>
    Yaqui,
    
    /// <remarks/>
    Yuman,
    
    /// <remarks/>
    [XmlEnumAttribute("Alaska Athabascan")]
    AlaskaAthabascan,
    
    /// <remarks/>
    Aleut,
    
    /// <remarks/>
    Eskimo,
    
    /// <remarks/>
    [XmlEnumAttribute("Tlingit-Haida")]
    TlingitHaida,
    
    /// <remarks/>
    Other,
}
}
#pragma warning restore
