// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum FAFSAStatusList
{
    
    /// <remarks/>
    Filed,
    
    /// <remarks/>
    [XmlEnumAttribute("Planning to file")]
    Planningtofile,
    
    /// <remarks/>
    [XmlEnumAttribute("Not planning to file")]
    Notplanningtofile,
    
    /// <remarks/>
    [XmlEnumAttribute("Unable to file")]
    Unabletofile,
    
    /// <remarks/>
    Other,
}
}
#pragma warning restore
