// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum FamilyTitlesList
{
    
    /// <remarks/>
    Spouse,
    
    /// <remarks/>
    Guardian,
    
    /// <remarks/>
    [XmlEnumAttribute("Significant Other")]
    SignificantOther,
    
    /// <remarks/>
    [XmlEnumAttribute("Domestic Partner")]
    DomesticPartner,
    
    /// <remarks/>
    Father,
    
    /// <remarks/>
    Mother,
    
    /// <remarks/>
    Grandfather,
    
    /// <remarks/>
    Grandmother,
    
    /// <remarks/>
    Son,
    
    /// <remarks/>
    Daughter,
    
    /// <remarks/>
    Fosterparent,
    
    /// <remarks/>
    Fosterchild,
    
    /// <remarks/>
    Grandson,
    
    /// <remarks/>
    Granddaughter,
    
    /// <remarks/>
    Brother,
    
    /// <remarks/>
    Sister,
    
    /// <remarks/>
    Uncle,
    
    /// <remarks/>
    Aunt,
    
    /// <remarks/>
    Cousin,
    
    /// <remarks/>
    Nephew,
    
    /// <remarks/>
    Niece,
    
    /// <remarks/>
    Stepfather,
    
    /// <remarks/>
    Stepmother,
    
    /// <remarks/>
    Stepson,
    
    /// <remarks/>
    Stepdaughter,
    
    /// <remarks/>
    Stepparent,
    
    /// <remarks/>
    Stepchild,
    
    /// <remarks/>
    Stepbrother,
    
    /// <remarks/>
    Stepsister,
    
    /// <remarks/>
    [XmlEnumAttribute("Father in law")]
    Fatherinlaw,
    
    /// <remarks/>
    [XmlEnumAttribute("Mother in law")]
    Motherinlaw,
    
    /// <remarks/>
    [XmlEnumAttribute("Son in law")]
    Soninlaw,
    
    /// <remarks/>
    [XmlEnumAttribute("Daughter in law")]
    Daughterinlaw,
    
    /// <remarks/>
    [XmlEnumAttribute("Parent in law")]
    Parentinlaw,
    
    /// <remarks/>
    [XmlEnumAttribute("Child in law")]
    Childinlaw,
    
    /// <remarks/>
    [XmlEnumAttribute("Brother in law")]
    Brotherinlaw,
    
    /// <remarks/>
    [XmlEnumAttribute("Sister in law")]
    Sisterinlaw,
    
    /// <remarks/>
    Other,
}
}
#pragma warning restore
