// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class GovernmentAid
{
    
    private List<GovernmentPrograms> _programs;
    
    private string _programOtherDesc;
    
    public GovernmentAid()
    {
        _programs = new List<GovernmentPrograms>();
    }
    
    [XmlElementAttribute("Programs")]
    public List<GovernmentPrograms> Programs
    {
        get
        {
            return _programs;
        }
        set
        {
            _programs = value;
        }
    }
    
    public string ProgramOtherDesc
    {
        get
        {
            return _programOtherDesc;
        }
        set
        {
            _programOtherDesc = value;
        }
    }
}
}
#pragma warning restore
