// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class GPA
{
    
    private string _schoolName;
    
    private SchoolTypesList _schoolType;
    
    private string _otherSchoolDesc;
    
    private bool _currentSchoolCalculatesGPA;
    
    private GPAInfo _cumulativeGPA;
    
    private List<GPAInfo> _gPAsPerSchoolYear;
    
    public GPA()
    {
        _gPAsPerSchoolYear = new List<GPAInfo>();
        _cumulativeGPA = new GPAInfo();
    }
    
    public string SchoolName
    {
        get
        {
            return _schoolName;
        }
        set
        {
            _schoolName = value;
        }
    }
    
    public SchoolTypesList SchoolType
    {
        get
        {
            return _schoolType;
        }
        set
        {
            _schoolType = value;
        }
    }
    
    public string OtherSchoolDesc
    {
        get
        {
            return _otherSchoolDesc;
        }
        set
        {
            _otherSchoolDesc = value;
        }
    }
    
    public bool CurrentSchoolCalculatesGPA
    {
        get
        {
            return _currentSchoolCalculatesGPA;
        }
        set
        {
            _currentSchoolCalculatesGPA = value;
        }
    }
    
    public GPAInfo CumulativeGPA
    {
        get
        {
            return _cumulativeGPA;
        }
        set
        {
            _cumulativeGPA = value;
        }
    }
    
    [XmlElementAttribute("GPAsPerSchoolYear")]
    public List<GPAInfo> GPAsPerSchoolYear
    {
        get
        {
            return _gPAsPerSchoolYear;
        }
        set
        {
            _gPAsPerSchoolYear = value;
        }
    }
}
}
#pragma warning restore
