// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class GPAInfo
{
    
    private SchoolYearsList _schoolYear;
    
    private string _gPA;
    
    private bool _weighted;
    
    private GradingScaleList _scale;
    
    private string _scaleOther;
    
    public SchoolYearsList SchoolYear
    {
        get
        {
            return _schoolYear;
        }
        set
        {
            _schoolYear = value;
        }
    }
    
    public string GPA
    {
        get
        {
            return _gPA;
        }
        set
        {
            _gPA = value;
        }
    }
    
    public bool Weighted
    {
        get
        {
            return _weighted;
        }
        set
        {
            _weighted = value;
        }
    }
    
    public GradingScaleList Scale
    {
        get
        {
            return _scale;
        }
        set
        {
            _scale = value;
        }
    }
    
    public string ScaleOther
    {
        get
        {
            return _scaleOther;
        }
        set
        {
            _scaleOther = value;
        }
    }
}
}
#pragma warning restore
