// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class GraduationInfo
{
    
    private bool _graduated;
    
    private SchoolProgramTypesList _graduationType;
    
    private string _graduationTypeOtherDesc;
    
    private string _graduationSchoolName;
    
    private System.DateTime _graduationDate;
    
    private string _graduationCity;
    
    private string _graduationCounty;
    
    private string _graduationStateorProvince;
    
    private string _graduationZIPOrPostalCode;
    
    private string _graduationCountry;
    
    public bool Graduated
    {
        get
        {
            return _graduated;
        }
        set
        {
            _graduated = value;
        }
    }
    
    public SchoolProgramTypesList GraduationType
    {
        get
        {
            return _graduationType;
        }
        set
        {
            _graduationType = value;
        }
    }
    
    public string GraduationTypeOtherDesc
    {
        get
        {
            return _graduationTypeOtherDesc;
        }
        set
        {
            _graduationTypeOtherDesc = value;
        }
    }
    
    public string GraduationSchoolName
    {
        get
        {
            return _graduationSchoolName;
        }
        set
        {
            _graduationSchoolName = value;
        }
    }
    
    [XmlElementAttribute(DataType="date")]
    public System.DateTime GraduationDate
    {
        get
        {
            return _graduationDate;
        }
        set
        {
            _graduationDate = value;
        }
    }
    
    public string GraduationCity
    {
        get
        {
            return _graduationCity;
        }
        set
        {
            _graduationCity = value;
        }
    }
    
    public string GraduationCounty
    {
        get
        {
            return _graduationCounty;
        }
        set
        {
            _graduationCounty = value;
        }
    }
    
    public string GraduationStateorProvince
    {
        get
        {
            return _graduationStateorProvince;
        }
        set
        {
            _graduationStateorProvince = value;
        }
    }
    
    public string GraduationZIPOrPostalCode
    {
        get
        {
            return _graduationZIPOrPostalCode;
        }
        set
        {
            _graduationZIPOrPostalCode = value;
        }
    }
    
    public string GraduationCountry
    {
        get
        {
            return _graduationCountry;
        }
        set
        {
            _graduationCountry = value;
        }
    }
}
}
#pragma warning restore
