// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum GradingScaleList
{
    
    /// <remarks/>
    [XmlEnumAttribute("4.0")]
    Item40,
    
    /// <remarks/>
    [XmlEnumAttribute("4.3")]
    Item43,
    
    /// <remarks/>
    [XmlEnumAttribute("5.0")]
    Item50,
    
    /// <remarks/>
    [XmlEnumAttribute("100")]
    Item100,
    
    /// <remarks/>
    Alphabetic,
    
    /// <remarks/>
    Other,
}
}
#pragma warning restore
