// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class HomeEnvironment
{
    
    private List<LivingWithList> _livingWith;
    
    private string _livingWithOtherDesc;
    
    private int _residentsInHomeCount;
    
    private string _nativeLanguage;
    
    public HomeEnvironment()
    {
        _livingWith = new List<LivingWithList>();
    }
    
    [XmlElementAttribute("LivingWith")]
    public List<LivingWithList> LivingWith
    {
        get
        {
            return _livingWith;
        }
        set
        {
            _livingWith = value;
        }
    }
    
    public string LivingWithOtherDesc
    {
        get
        {
            return _livingWithOtherDesc;
        }
        set
        {
            _livingWithOtherDesc = value;
        }
    }
    
    public int ResidentsInHomeCount
    {
        get
        {
            return _residentsInHomeCount;
        }
        set
        {
            _residentsInHomeCount = value;
        }
    }
    
    public string NativeLanguage
    {
        get
        {
            return _nativeLanguage;
        }
        set
        {
            _nativeLanguage = value;
        }
    }
}
}
#pragma warning restore
