// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum LivingWithList
{
    
    /// <remarks/>
    Alone,
    
    /// <remarks/>
    Mother,
    
    /// <remarks/>
    Father,
    
    /// <remarks/>
    [XmlEnumAttribute("Step-parents")]
    Stepparents,
    
    /// <remarks/>
    Sibling,
    
    /// <remarks/>
    Grandparents,
    
    /// <remarks/>
    Guardian,
    
    /// <remarks/>
    [XmlEnumAttribute("Adopted family")]
    Adoptedfamily,
    
    /// <remarks/>
    [XmlEnumAttribute("Foster family")]
    Fosterfamily,
    
    /// <remarks/>
    [XmlEnumAttribute("Other relatives")]
    Otherrelatives,
    
    /// <remarks/>
    [XmlEnumAttribute("Spouse or significant other")]
    Spouseorsignificantother,
    
    /// <remarks/>
    [XmlEnumAttribute("Your children")]
    Yourchildren,
    
    /// <remarks/>
    Friends,
    
    /// <remarks/>
    [XmlEnumAttribute("Group home")]
    Grouphome,
    
    /// <remarks/>
    Homeless,
    
    /// <remarks/>
    Other,
}
}
#pragma warning restore
