// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class Major
{
    
    private string _majorName;
    
    private int _majorRank;
    
    public string MajorName
    {
        get
        {
            return _majorName;
        }
        set
        {
            _majorName = value;
        }
    }
    
    public int MajorRank
    {
        get
        {
            return _majorRank;
        }
        set
        {
            _majorRank = value;
        }
    }
}
}
#pragma warning restore
