// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum MaritalStatusList
{
    
    /// <remarks/>
    Single,
    
    /// <remarks/>
    Married,
    
    /// <remarks/>
    [XmlEnumAttribute("Re-Married")]
    ReMarried,
    
    /// <remarks/>
    Divorced,
    
    /// <remarks/>
    [XmlEnumAttribute("Legally Separated")]
    LegallySeparated,
    
    /// <remarks/>
    [XmlEnumAttribute("Informally Separated")]
    InformallySeparated,
    
    /// <remarks/>
    Widowed,
    
    /// <remarks/>
    Deceased,
    
    /// <remarks/>
    Other,
}
}
#pragma warning restore
