// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum MilitaryBranchList
{
    
    /// <remarks/>
    Army,
    
    /// <remarks/>
    Navy,
    
    /// <remarks/>
    [XmlEnumAttribute("Air Force")]
    AirForce,
    
    /// <remarks/>
    Marines,
    
    /// <remarks/>
    [XmlEnumAttribute("Coast Guard")]
    CoastGuard,
    
    /// <remarks/>
    [XmlEnumAttribute("National Guard")]
    NationalGuard,
    
    /// <remarks/>
    [XmlEnumAttribute("Army Reserve")]
    ArmyReserve,
    
    /// <remarks/>
    [XmlEnumAttribute("Navy Reserve")]
    NavyReserve,
    
    /// <remarks/>
    [XmlEnumAttribute("Air Force Reserve")]
    AirForceReserve,
    
    /// <remarks/>
    [XmlEnumAttribute("Marines Reserve")]
    MarinesReserve,
    
    /// <remarks/>
    [XmlEnumAttribute("Coast Guard Reserve")]
    CoastGuardReserve,
    
    /// <remarks/>
    [XmlEnumAttribute("National Guard Reserve")]
    NationalGuardReserve,
    
    /// <remarks/>
    Other,
}
}
#pragma warning restore
