// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class Money
{
    
    private decimal _amount;
    
    private CurrencyList _currency;
    
    public decimal Amount
    {
        get
        {
            return _amount;
        }
        set
        {
            _amount = value;
        }
    }
    
    public CurrencyList Currency
    {
        get
        {
            return _currency;
        }
        set
        {
            _currency = value;
        }
    }
}
}
#pragma warning restore
