// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class Reference
{
    
    private Name _referenceName;
    
    private ContactInfo _referenceContactInfo;
    
    private RelationshipList _relationship;
    
    private string _relationshipOtherDesc;
    
    private int _yearsKnown;
    
    private string _titleOrOccupation;
    
    private string _companyName;
    
    private Address _referenceAddress;
    
    public Reference()
    {
        _referenceAddress = new Address();
        _referenceContactInfo = new ContactInfo();
        _referenceName = new Name();
    }
    
    public Name ReferenceName
    {
        get
        {
            return _referenceName;
        }
        set
        {
            _referenceName = value;
        }
    }
    
    public ContactInfo ReferenceContactInfo
    {
        get
        {
            return _referenceContactInfo;
        }
        set
        {
            _referenceContactInfo = value;
        }
    }
    
    public RelationshipList Relationship
    {
        get
        {
            return _relationship;
        }
        set
        {
            _relationship = value;
        }
    }
    
    public string RelationshipOtherDesc
    {
        get
        {
            return _relationshipOtherDesc;
        }
        set
        {
            _relationshipOtherDesc = value;
        }
    }
    
    public int YearsKnown
    {
        get
        {
            return _yearsKnown;
        }
        set
        {
            _yearsKnown = value;
        }
    }
    
    public string TitleOrOccupation
    {
        get
        {
            return _titleOrOccupation;
        }
        set
        {
            _titleOrOccupation = value;
        }
    }
    
    public string CompanyName
    {
        get
        {
            return _companyName;
        }
        set
        {
            _companyName = value;
        }
    }
    
    public Address ReferenceAddress
    {
        get
        {
            return _referenceAddress;
        }
        set
        {
            _referenceAddress = value;
        }
    }
}
}
#pragma warning restore
