// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class Relative
{
    
    private Name _relativeName;
    
    private FamilyTitlesList _relation;
    
    private string _relationOtherDesc;
    
    private bool _living;
    
    private System.DateTime _birthDate;
    
    private MaritalStatusList _maritalStatus;
    
    private bool _employed;
    
    private string _titleOrOccupation;
    
    private string _companyName;
    
    private Money _relativeIncome;
    
    private bool _disabled;
    
    private string _disabilityDesc;
    
    private int _workingHoursPerWeek;
    
    private EducationLevel _relativeEducationLevel;
    
    public Relative()
    {
        _relativeEducationLevel = new EducationLevel();
        _relativeIncome = new Money();
        _relativeName = new Name();
    }
    
    public Name RelativeName
    {
        get
        {
            return _relativeName;
        }
        set
        {
            _relativeName = value;
        }
    }
    
    public FamilyTitlesList Relation
    {
        get
        {
            return _relation;
        }
        set
        {
            _relation = value;
        }
    }
    
    public string RelationOtherDesc
    {
        get
        {
            return _relationOtherDesc;
        }
        set
        {
            _relationOtherDesc = value;
        }
    }
    
    public bool Living
    {
        get
        {
            return _living;
        }
        set
        {
            _living = value;
        }
    }
    
    [XmlElementAttribute(DataType="date")]
    public System.DateTime BirthDate
    {
        get
        {
            return _birthDate;
        }
        set
        {
            _birthDate = value;
        }
    }
    
    public MaritalStatusList MaritalStatus
    {
        get
        {
            return _maritalStatus;
        }
        set
        {
            _maritalStatus = value;
        }
    }
    
    public bool Employed
    {
        get
        {
            return _employed;
        }
        set
        {
            _employed = value;
        }
    }
    
    public string TitleOrOccupation
    {
        get
        {
            return _titleOrOccupation;
        }
        set
        {
            _titleOrOccupation = value;
        }
    }
    
    public string CompanyName
    {
        get
        {
            return _companyName;
        }
        set
        {
            _companyName = value;
        }
    }
    
    public Money RelativeIncome
    {
        get
        {
            return _relativeIncome;
        }
        set
        {
            _relativeIncome = value;
        }
    }
    
    public bool Disabled
    {
        get
        {
            return _disabled;
        }
        set
        {
            _disabled = value;
        }
    }
    
    public string DisabilityDesc
    {
        get
        {
            return _disabilityDesc;
        }
        set
        {
            _disabilityDesc = value;
        }
    }
    
    public int WorkingHoursPerWeek
    {
        get
        {
            return _workingHoursPerWeek;
        }
        set
        {
            _workingHoursPerWeek = value;
        }
    }
    
    public EducationLevel RelativeEducationLevel
    {
        get
        {
            return _relativeEducationLevel;
        }
        set
        {
            _relativeEducationLevel = value;
        }
    }
}
}
#pragma warning restore
