// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum SchoolYearsList
{
    
    /// <remarks/>
    [XmlEnumAttribute("High School Grade 9")]
    HighSchoolGrade9,
    
    /// <remarks/>
    [XmlEnumAttribute("High School Grade 10")]
    HighSchoolGrade10,
    
    /// <remarks/>
    [XmlEnumAttribute("High School Grade 11")]
    HighSchoolGrade11,
    
    /// <remarks/>
    [XmlEnumAttribute("High School Grade 12")]
    HighSchoolGrade12,
    
    /// <remarks/>
    [XmlEnumAttribute("College Year 1")]
    CollegeYear1,
    
    /// <remarks/>
    [XmlEnumAttribute("College Year 2")]
    CollegeYear2,
    
    /// <remarks/>
    [XmlEnumAttribute("College Year 3")]
    CollegeYear3,
    
    /// <remarks/>
    [XmlEnumAttribute("College Year 4")]
    CollegeYear4,
    
    /// <remarks/>
    [XmlEnumAttribute("College Year 5")]
    CollegeYear5,
    
    /// <remarks/>
    [XmlEnumAttribute("College Year 6")]
    CollegeYear6,
    
    /// <remarks/>
    [XmlEnumAttribute("College Year 7")]
    CollegeYear7,
    
    /// <remarks/>
    [XmlEnumAttribute("College Year 8")]
    CollegeYear8,
    
    /// <remarks/>
    [XmlEnumAttribute("Graduate School Year 1")]
    GraduateSchoolYear1,
    
    /// <remarks/>
    [XmlEnumAttribute("Graduate School Year 2")]
    GraduateSchoolYear2,
    
    /// <remarks/>
    [XmlEnumAttribute("Graduate School Year 3")]
    GraduateSchoolYear3,
    
    /// <remarks/>
    [XmlEnumAttribute("Graduate School Year 4")]
    GraduateSchoolYear4,
    
    /// <remarks/>
    Other,
}
}
#pragma warning restore
