// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum SchoolTypesList
{
    
    /// <remarks/>
    [XmlEnumAttribute("Elementary school")]
    Elementaryschool,
    
    /// <remarks/>
    [XmlEnumAttribute("Middle school")]
    Middleschool,
    
    /// <remarks/>
    [XmlEnumAttribute("High school")]
    Highschool,
    
    /// <remarks/>
    [XmlEnumAttribute("Technical school")]
    Technicalschool,
    
    /// <remarks/>
    College,
    
    /// <remarks/>
    University,
    
    /// <remarks/>
    [XmlEnumAttribute("Home school")]
    Homeschool,
    
    /// <remarks/>
    [XmlEnumAttribute("Graduate school")]
    Graduateschool,
    
    /// <remarks/>
    [XmlEnumAttribute("Other school")]
    Otherschool,
}
}
#pragma warning restore
