// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class School
{
    
    private string _schoolName;
    
    private string _nCESCode;
    
    private string _cEEBCode;
    
    private SchoolTypesList _schoolType;
    
    private string _otherSchoolDesc;
    
    private Address _schoolAddress;
    
    public School()
    {
        _schoolAddress = new Address();
    }
    
    public string SchoolName
    {
        get
        {
            return _schoolName;
        }
        set
        {
            _schoolName = value;
        }
    }
    
    public string NCESCode
    {
        get
        {
            return _nCESCode;
        }
        set
        {
            _nCESCode = value;
        }
    }
    
    public string CEEBCode
    {
        get
        {
            return _cEEBCode;
        }
        set
        {
            _cEEBCode = value;
        }
    }
    
    public SchoolTypesList SchoolType
    {
        get
        {
            return _schoolType;
        }
        set
        {
            _schoolType = value;
        }
    }
    
    public string OtherSchoolDesc
    {
        get
        {
            return _otherSchoolDesc;
        }
        set
        {
            _otherSchoolDesc = value;
        }
    }
    
    public Address SchoolAddress
    {
        get
        {
            return _schoolAddress;
        }
        set
        {
            _schoolAddress = value;
        }
    }
}
}
#pragma warning restore
