// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum ScholarshipPurposeList
{
    
    /// <remarks/>
    [XmlEnumAttribute("High school")]
    Highschool,
    
    /// <remarks/>
    [XmlEnumAttribute("Certificate program")]
    Certificateprogram,
    
    /// <remarks/>
    [XmlEnumAttribute("2-year program")]
    Item2yearprogram,
    
    /// <remarks/>
    [XmlEnumAttribute("4-year program")]
    Item4yearprogram,
    
    /// <remarks/>
    [XmlEnumAttribute("Graduate program")]
    Graduateprogram,
    
    /// <remarks/>
    Other,
}
}
#pragma warning restore
