// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class ScholarshipPurpose
{
    
    private ScholarshipPurposeList _purpose;
    
    private string _purposeOtherDesc;
    
    public ScholarshipPurposeList Purpose
    {
        get
        {
            return _purpose;
        }
        set
        {
            _purpose = value;
        }
    }
    
    public string PurposeOtherDesc
    {
        get
        {
            return _purposeOtherDesc;
        }
        set
        {
            _purposeOtherDesc = value;
        }
    }
}
}
#pragma warning restore
