// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class Spouse
{
    
    private Name _spouseName;
    
    private bool _employed;
    
    private string _titleOrOccupation;
    
    private string _companyName;
    
    private Money _spouseIncome;
    
    private bool _disabled;
    
    private string _disabilityDesc;
    
    private int _workingHoursPerWeek;
    
    private EducationLevel _spouseEducationLevel;
    
    public Spouse()
    {
        _spouseEducationLevel = new EducationLevel();
        _spouseIncome = new Money();
        _spouseName = new Name();
    }
    
    public Name SpouseName
    {
        get
        {
            return _spouseName;
        }
        set
        {
            _spouseName = value;
        }
    }
    
    public bool Employed
    {
        get
        {
            return _employed;
        }
        set
        {
            _employed = value;
        }
    }
    
    public string TitleOrOccupation
    {
        get
        {
            return _titleOrOccupation;
        }
        set
        {
            _titleOrOccupation = value;
        }
    }
    
    public string CompanyName
    {
        get
        {
            return _companyName;
        }
        set
        {
            _companyName = value;
        }
    }
    
    public Money SpouseIncome
    {
        get
        {
            return _spouseIncome;
        }
        set
        {
            _spouseIncome = value;
        }
    }
    
    public bool Disabled
    {
        get
        {
            return _disabled;
        }
        set
        {
            _disabled = value;
        }
    }
    
    public string DisabilityDesc
    {
        get
        {
            return _disabilityDesc;
        }
        set
        {
            _disabilityDesc = value;
        }
    }
    
    public int WorkingHoursPerWeek
    {
        get
        {
            return _workingHoursPerWeek;
        }
        set
        {
            _workingHoursPerWeek = value;
        }
    }
    
    public EducationLevel SpouseEducationLevel
    {
        get
        {
            return _spouseEducationLevel;
        }
        set
        {
            _spouseEducationLevel = value;
        }
    }
}
}
#pragma warning restore
