// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class Student
{
    
    private Name _name;
    
    private ContactInfo _contactInfo;
    
    private string _studentCustomId;
    
    private List<Address> _addresses;
    
    private string _timeAtCurrentAddress;
    
    private System.DateTime _birthDate;
    
    private GenderList _gender;
    
    private GenderDetailList _genderDetail;
    
    private OrientationList _orientation;
    
    private Race _race;
    
    private Ethnicity _ethnicity;
    
    private BirthPlace _birthPlace;
    
    private Citizenship _citizenship;
    
    private bool _disabled;
    
    private string _disabilityDesc;
    
    private bool _veteran;
    
    private List<MilitaryBranchList> _veteranDesc;
    
    private bool _pOW;
    
    private string _pOWDesc;
    
    private bool _childofPOWMIA;
    
    private EducationLevel _educationLevel;
    
    private List<TestScore> _testScores;
    
    private List<GraduationInfo> _graduationInfo;
    
    private List<GPA> _gPA;
    
    private List<ClassRank> _classRank;
    
    private List<Enrollment> _currentEnrollments;
    
    private List<CollegeChoice> _collegeChoices;
    
    private CollegeChoice _finalCollegeChoice;
    
    private ScholarshipPurpose _scholarshipPurpose;
    
    private bool _applyingForOtherScholarships;
    
    private List<Major> _intendedMajors;
    
    private List<Major> _currentMajors;
    
    private List<string> _intendedDiscipline;
    
    private List<Essay> _essays;
    
    private List<Activity> _activities;
    
    private bool _employed;
    
    private Money _income;
    
    private Money _fAFSAParentsCash;
    
    private Money _fAFSAParentsNetWorth;
    
    private Money _fAFSAParentsBusinessInvestments;
    
    private FAFSAStatusList _fAFSAStatus;
    
    private string _fAFSAStatusDesc;
    
    private decimal _fAFSAEFC;
    
    private CurrencyList _fAFSAEFCCurrency;
    
    private string _fAFSAFilingYear;
    
    private bool _disciplineOrLegal;
    
    private MaritalStatusList _maritalStatus;
    
    private Spouse _spouse;
    
    private DependencyStatusList _dependencyStatus;
    
    private int _dependentsCount;
    
    private HomeEnvironment _homeEnvironment;
    
    private int _familyMembersInCollegeCount;
    
    private int _siblingsCount;
    
    private List<Relative> _parents;
    
    private GovernmentAid _governmentAidParticipation;
    
    private List<CollegeReadinessProgram> _collegeReadinessPrograms;
    
    private List<Reference> _studentReferences;
    
    private List<Class> _simpleTranscript;
    
    public Student()
    {
        _simpleTranscript = new List<Class>();
        _studentReferences = new List<Reference>();
        _collegeReadinessPrograms = new List<CollegeReadinessProgram>();
        _governmentAidParticipation = new GovernmentAid();
        _parents = new List<Relative>();
        _homeEnvironment = new HomeEnvironment();
        _spouse = new Spouse();
        _fAFSAParentsBusinessInvestments = new Money();
        _fAFSAParentsNetWorth = new Money();
        _fAFSAParentsCash = new Money();
        _income = new Money();
        _activities = new List<Activity>();
        _essays = new List<Essay>();
        _intendedDiscipline = new List<string>();
        _currentMajors = new List<Major>();
        _intendedMajors = new List<Major>();
        _scholarshipPurpose = new ScholarshipPurpose();
        _finalCollegeChoice = new CollegeChoice();
        _collegeChoices = new List<CollegeChoice>();
        _currentEnrollments = new List<Enrollment>();
        _classRank = new List<ClassRank>();
        _gPA = new List<GPA>();
        _graduationInfo = new List<GraduationInfo>();
        _testScores = new List<TestScore>();
        _educationLevel = new EducationLevel();
        _veteranDesc = new List<MilitaryBranchList>();
        _citizenship = new Citizenship();
        _birthPlace = new BirthPlace();
        _ethnicity = new Ethnicity();
        _race = new Race();
        _addresses = new List<Address>();
        _contactInfo = new ContactInfo();
        _name = new Name();
    }
    
    public Name Name
    {
        get
        {
            return _name;
        }
        set
        {
            _name = value;
        }
    }
    
    public ContactInfo ContactInfo
    {
        get
        {
            return _contactInfo;
        }
        set
        {
            _contactInfo = value;
        }
    }
    
    public string StudentCustomId
    {
        get
        {
            return _studentCustomId;
        }
        set
        {
            _studentCustomId = value;
        }
    }
    
    [XmlElementAttribute("Addresses")]
    public List<Address> Addresses
    {
        get
        {
            return _addresses;
        }
        set
        {
            _addresses = value;
        }
    }
    
    [XmlElementAttribute(DataType="duration")]
    public string TimeAtCurrentAddress
    {
        get
        {
            return _timeAtCurrentAddress;
        }
        set
        {
            _timeAtCurrentAddress = value;
        }
    }
    
    [XmlElementAttribute(DataType="date")]
    public System.DateTime BirthDate
    {
        get
        {
            return _birthDate;
        }
        set
        {
            _birthDate = value;
        }
    }
    
    public GenderList Gender
    {
        get
        {
            return _gender;
        }
        set
        {
            _gender = value;
        }
    }
    
    public GenderDetailList GenderDetail
    {
        get
        {
            return _genderDetail;
        }
        set
        {
            _genderDetail = value;
        }
    }
    
    public OrientationList Orientation
    {
        get
        {
            return _orientation;
        }
        set
        {
            _orientation = value;
        }
    }
    
    public Race Race
    {
        get
        {
            return _race;
        }
        set
        {
            _race = value;
        }
    }
    
    public Ethnicity Ethnicity
    {
        get
        {
            return _ethnicity;
        }
        set
        {
            _ethnicity = value;
        }
    }
    
    public BirthPlace BirthPlace
    {
        get
        {
            return _birthPlace;
        }
        set
        {
            _birthPlace = value;
        }
    }
    
    public Citizenship Citizenship
    {
        get
        {
            return _citizenship;
        }
        set
        {
            _citizenship = value;
        }
    }
    
    public bool Disabled
    {
        get
        {
            return _disabled;
        }
        set
        {
            _disabled = value;
        }
    }
    
    public string DisabilityDesc
    {
        get
        {
            return _disabilityDesc;
        }
        set
        {
            _disabilityDesc = value;
        }
    }
    
    public bool Veteran
    {
        get
        {
            return _veteran;
        }
        set
        {
            _veteran = value;
        }
    }
    
    [XmlElementAttribute("VeteranDesc")]
    public List<MilitaryBranchList> VeteranDesc
    {
        get
        {
            return _veteranDesc;
        }
        set
        {
            _veteranDesc = value;
        }
    }
    
    public bool POW
    {
        get
        {
            return _pOW;
        }
        set
        {
            _pOW = value;
        }
    }
    
    public string POWDesc
    {
        get
        {
            return _pOWDesc;
        }
        set
        {
            _pOWDesc = value;
        }
    }
    
    public bool ChildofPOWMIA
    {
        get
        {
            return _childofPOWMIA;
        }
        set
        {
            _childofPOWMIA = value;
        }
    }
    
    public EducationLevel EducationLevel
    {
        get
        {
            return _educationLevel;
        }
        set
        {
            _educationLevel = value;
        }
    }
    
    [XmlElementAttribute("TestScores")]
    public List<TestScore> TestScores
    {
        get
        {
            return _testScores;
        }
        set
        {
            _testScores = value;
        }
    }
    
    [XmlElementAttribute("GraduationInfo")]
    public List<GraduationInfo> GraduationInfo
    {
        get
        {
            return _graduationInfo;
        }
        set
        {
            _graduationInfo = value;
        }
    }
    
    [XmlElementAttribute("GPA")]
    public List<GPA> GPA
    {
        get
        {
            return _gPA;
        }
        set
        {
            _gPA = value;
        }
    }
    
    [XmlElementAttribute("ClassRank")]
    public List<ClassRank> ClassRank
    {
        get
        {
            return _classRank;
        }
        set
        {
            _classRank = value;
        }
    }
    
    [XmlElementAttribute("CurrentEnrollments")]
    public List<Enrollment> CurrentEnrollments
    {
        get
        {
            return _currentEnrollments;
        }
        set
        {
            _currentEnrollments = value;
        }
    }
    
    [XmlElementAttribute("CollegeChoices")]
    public List<CollegeChoice> CollegeChoices
    {
        get
        {
            return _collegeChoices;
        }
        set
        {
            _collegeChoices = value;
        }
    }
    
    public CollegeChoice FinalCollegeChoice
    {
        get
        {
            return _finalCollegeChoice;
        }
        set
        {
            _finalCollegeChoice = value;
        }
    }
    
    public ScholarshipPurpose ScholarshipPurpose
    {
        get
        {
            return _scholarshipPurpose;
        }
        set
        {
            _scholarshipPurpose = value;
        }
    }
    
    public bool ApplyingForOtherScholarships
    {
        get
        {
            return _applyingForOtherScholarships;
        }
        set
        {
            _applyingForOtherScholarships = value;
        }
    }
    
    [XmlElementAttribute("IntendedMajors")]
    public List<Major> IntendedMajors
    {
        get
        {
            return _intendedMajors;
        }
        set
        {
            _intendedMajors = value;
        }
    }
    
    [XmlElementAttribute("CurrentMajors")]
    public List<Major> CurrentMajors
    {
        get
        {
            return _currentMajors;
        }
        set
        {
            _currentMajors = value;
        }
    }
    
    [XmlElementAttribute("IntendedDiscipline")]
    public List<string> IntendedDiscipline
    {
        get
        {
            return _intendedDiscipline;
        }
        set
        {
            _intendedDiscipline = value;
        }
    }
    
    [XmlElementAttribute("Essays")]
    public List<Essay> Essays
    {
        get
        {
            return _essays;
        }
        set
        {
            _essays = value;
        }
    }
    
    [XmlElementAttribute("Activities")]
    public List<Activity> Activities
    {
        get
        {
            return _activities;
        }
        set
        {
            _activities = value;
        }
    }
    
    public bool Employed
    {
        get
        {
            return _employed;
        }
        set
        {
            _employed = value;
        }
    }
    
    public Money Income
    {
        get
        {
            return _income;
        }
        set
        {
            _income = value;
        }
    }
    
    public Money FAFSAParentsCash
    {
        get
        {
            return _fAFSAParentsCash;
        }
        set
        {
            _fAFSAParentsCash = value;
        }
    }
    
    public Money FAFSAParentsNetWorth
    {
        get
        {
            return _fAFSAParentsNetWorth;
        }
        set
        {
            _fAFSAParentsNetWorth = value;
        }
    }
    
    public Money FAFSAParentsBusinessInvestments
    {
        get
        {
            return _fAFSAParentsBusinessInvestments;
        }
        set
        {
            _fAFSAParentsBusinessInvestments = value;
        }
    }
    
    public FAFSAStatusList FAFSAStatus
    {
        get
        {
            return _fAFSAStatus;
        }
        set
        {
            _fAFSAStatus = value;
        }
    }
    
    public string FAFSAStatusDesc
    {
        get
        {
            return _fAFSAStatusDesc;
        }
        set
        {
            _fAFSAStatusDesc = value;
        }
    }
    
    public decimal FAFSAEFC
    {
        get
        {
            return _fAFSAEFC;
        }
        set
        {
            _fAFSAEFC = value;
        }
    }
    
    public CurrencyList FAFSAEFCCurrency
    {
        get
        {
            return _fAFSAEFCCurrency;
        }
        set
        {
            _fAFSAEFCCurrency = value;
        }
    }
    
    public string FAFSAFilingYear
    {
        get
        {
            return _fAFSAFilingYear;
        }
        set
        {
            _fAFSAFilingYear = value;
        }
    }
    
    public bool DisciplineOrLegal
    {
        get
        {
            return _disciplineOrLegal;
        }
        set
        {
            _disciplineOrLegal = value;
        }
    }
    
    public MaritalStatusList MaritalStatus
    {
        get
        {
            return _maritalStatus;
        }
        set
        {
            _maritalStatus = value;
        }
    }
    
    public Spouse Spouse
    {
        get
        {
            return _spouse;
        }
        set
        {
            _spouse = value;
        }
    }
    
    public DependencyStatusList DependencyStatus
    {
        get
        {
            return _dependencyStatus;
        }
        set
        {
            _dependencyStatus = value;
        }
    }
    
    public int DependentsCount
    {
        get
        {
            return _dependentsCount;
        }
        set
        {
            _dependentsCount = value;
        }
    }
    
    public HomeEnvironment HomeEnvironment
    {
        get
        {
            return _homeEnvironment;
        }
        set
        {
            _homeEnvironment = value;
        }
    }
    
    public int FamilyMembersInCollegeCount
    {
        get
        {
            return _familyMembersInCollegeCount;
        }
        set
        {
            _familyMembersInCollegeCount = value;
        }
    }
    
    public int SiblingsCount
    {
        get
        {
            return _siblingsCount;
        }
        set
        {
            _siblingsCount = value;
        }
    }
    
    [XmlElementAttribute("Parents")]
    public List<Relative> Parents
    {
        get
        {
            return _parents;
        }
        set
        {
            _parents = value;
        }
    }
    
    public GovernmentAid GovernmentAidParticipation
    {
        get
        {
            return _governmentAidParticipation;
        }
        set
        {
            _governmentAidParticipation = value;
        }
    }
    
    [XmlElementAttribute("CollegeReadinessPrograms")]
    public List<CollegeReadinessProgram> CollegeReadinessPrograms
    {
        get
        {
            return _collegeReadinessPrograms;
        }
        set
        {
            _collegeReadinessPrograms = value;
        }
    }
    
    [XmlElementAttribute("StudentReferences")]
    public List<Reference> StudentReferences
    {
        get
        {
            return _studentReferences;
        }
        set
        {
            _studentReferences = value;
        }
    }
    
    [XmlElementAttribute("SimpleTranscript")]
    public List<Class> SimpleTranscript
    {
        get
        {
            return _simpleTranscript;
        }
        set
        {
            _simpleTranscript = value;
        }
    }
}
}
#pragma warning restore
