// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public partial class TestScore
{
    
    private TestsList _test;
    
    private string _testOtherDesc;
    
    private decimal _score;
    
    private ScoreTypes _scoreType;
    
    private ScoreNumericTypes _scoreNumericType;
    
    private System.DateTime _scoreDate;
    
    public TestsList Test
    {
        get
        {
            return _test;
        }
        set
        {
            _test = value;
        }
    }
    
    public string TestOtherDesc
    {
        get
        {
            return _testOtherDesc;
        }
        set
        {
            _testOtherDesc = value;
        }
    }
    
    public decimal Score
    {
        get
        {
            return _score;
        }
        set
        {
            _score = value;
        }
    }
    
    public ScoreTypes ScoreType
    {
        get
        {
            return _scoreType;
        }
        set
        {
            _scoreType = value;
        }
    }
    
    public ScoreNumericTypes ScoreNumericType
    {
        get
        {
            return _scoreNumericType;
        }
        set
        {
            _scoreNumericType = value;
        }
    }
    
    [XmlElementAttribute(DataType="date")]
    public System.DateTime ScoreDate
    {
        get
        {
            return _scoreDate;
        }
        set
        {
            _scoreDate = value;
        }
    }
}
}
#pragma warning restore
