// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SSSDK
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://scholarshipproviders.org/scholarshipapplication")]
public enum TestsList
{
    
    /// <remarks/>
    [XmlEnumAttribute("SAT Critical Reading")]
    SATCriticalReading,
    
    /// <remarks/>
    [XmlEnumAttribute("SAT Verbal (Obsolete)")]
    SATVerbalObsolete,
    
    /// <remarks/>
    [XmlEnumAttribute("SAT Math")]
    SATMath,
    
    /// <remarks/>
    [XmlEnumAttribute("SAT Writing")]
    SATWriting,
    
    /// <remarks/>
    [XmlEnumAttribute("ACT Composite")]
    ACTComposite,
    
    /// <remarks/>
    [XmlEnumAttribute("ACT English")]
    ACTEnglish,
    
    /// <remarks/>
    [XmlEnumAttribute("ACT Math")]
    ACTMath,
    
    /// <remarks/>
    [XmlEnumAttribute("ACT Reading")]
    ACTReading,
    
    /// <remarks/>
    [XmlEnumAttribute("ACT Science")]
    ACTScience,
    
    /// <remarks/>
    [XmlEnumAttribute("ACT Writing")]
    ACTWriting,
    
    /// <remarks/>
    [XmlEnumAttribute("PSAT Critical Reading")]
    PSATCriticalReading,
    
    /// <remarks/>
    [XmlEnumAttribute("PSAT Verbal (Obsolete)")]
    PSATVerbalObsolete,
    
    /// <remarks/>
    [XmlEnumAttribute("PSAT Math")]
    PSATMath,
    
    /// <remarks/>
    [XmlEnumAttribute("PSAT Writing")]
    PSATWriting,
    
    /// <remarks/>
    [XmlEnumAttribute("PSAT Selection Index")]
    PSATSelectionIndex,
    
    /// <remarks/>
    [XmlEnumAttribute("GMAT Verbal")]
    GMATVerbal,
    
    /// <remarks/>
    [XmlEnumAttribute("GMAT Quantitative")]
    GMATQuantitative,
    
    /// <remarks/>
    [XmlEnumAttribute("GMAT Analytical Writing Assessment")]
    GMATAnalyticalWritingAssessment,
    
    /// <remarks/>
    [XmlEnumAttribute("GRE Verbal")]
    GREVerbal,
    
    /// <remarks/>
    [XmlEnumAttribute("GRE Quantitative")]
    GREQuantitative,
    
    /// <remarks/>
    [XmlEnumAttribute("LSAT Verbal")]
    LSATVerbal,
    
    /// <remarks/>
    [XmlEnumAttribute("LSAT Quant")]
    LSATQuant,
    
    /// <remarks/>
    [XmlEnumAttribute("LSAT Analytic")]
    LSATAnalytic,
    
    /// <remarks/>
    [XmlEnumAttribute("TOEFL Listening")]
    TOEFLListening,
    
    /// <remarks/>
    [XmlEnumAttribute("TOEFL Structure/Writing")]
    TOEFLStructureWriting,
    
    /// <remarks/>
    [XmlEnumAttribute("TOEFL Reading")]
    TOEFLReading,
    
    /// <remarks/>
    [XmlEnumAttribute("TOEFL Total Score")]
    TOEFLTotalScore,
    
    /// <remarks/>
    [XmlEnumAttribute("MCAT Verbal Reasoning")]
    MCATVerbalReasoning,
    
    /// <remarks/>
    [XmlEnumAttribute("MCAT Physical Sciences")]
    MCATPhysicalSciences,
    
    /// <remarks/>
    [XmlEnumAttribute("MCAT Writing Sample")]
    MCATWritingSample,
    
    /// <remarks/>
    [XmlEnumAttribute("MCAT Biological Sciences")]
    MCATBiologicalSciences,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Art History")]
    APArtHistory,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Biology")]
    APBiology,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Calculus AB")]
    APCalculusAB,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Calculus BC")]
    APCalculusBC,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Chemistry")]
    APChemistry,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Chinese Language and Culture")]
    APChineseLanguageandCulture,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Computer Science A")]
    APComputerScienceA,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Computer Science AB")]
    APComputerScienceAB,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Macroeconomics")]
    APMacroeconomics,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Microeconomics")]
    APMicroeconomics,
    
    /// <remarks/>
    [XmlEnumAttribute("AP English Language")]
    APEnglishLanguage,
    
    /// <remarks/>
    [XmlEnumAttribute("AP English Literature")]
    APEnglishLiterature,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Environmental Science")]
    APEnvironmentalScience,
    
    /// <remarks/>
    [XmlEnumAttribute("AP European History")]
    APEuropeanHistory,
    
    /// <remarks/>
    [XmlEnumAttribute("AP French Language")]
    APFrenchLanguage,
    
    /// <remarks/>
    [XmlEnumAttribute("AP French Literature")]
    APFrenchLiterature,
    
    /// <remarks/>
    [XmlEnumAttribute("AP German Language")]
    APGermanLanguage,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Comp Government and Politics")]
    APCompGovernmentandPolitics,
    
    /// <remarks/>
    [XmlEnumAttribute("AP U.S. Government and Politics")]
    APUSGovernmentandPolitics,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Human Geography")]
    APHumanGeography,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Italian Language and Culture")]
    APItalianLanguageandCulture,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Japanese Language and Culture")]
    APJapaneseLanguageandCulture,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Latin Literature")]
    APLatinLiterature,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Latin: Vergil")]
    APLatinVergil,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Music Theory")]
    APMusicTheory,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Physics B")]
    APPhysicsB,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Physics C")]
    APPhysicsC,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Psychology")]
    APPsychology,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Spanish Language")]
    APSpanishLanguage,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Spanish Literature")]
    APSpanishLiterature,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Statistics")]
    APStatistics,
    
    /// <remarks/>
    [XmlEnumAttribute("AP Studio Art")]
    APStudioArt,
    
    /// <remarks/>
    [XmlEnumAttribute("AP U.S. History")]
    APUSHistory,
    
    /// <remarks/>
    [XmlEnumAttribute("AP World History ")]
    APWorldHistory,
    
    /// <remarks/>
    [XmlEnumAttribute("GED Score")]
    GEDScore,
    
    /// <remarks/>
    Other,
}
}
#pragma warning restore
